### ISSUE TITLE
using link_to with block in arbre template

### ISSUE THREAD

**Issue by senid231** [activeadmin/arbre#46]
index.html.arb with such code

``` ruby
h1 'Dashboard#index'
para 'Find me in app/views/dashboard/index.html.arb'
link_to sign_out_path, data: {confirm: 'Are you sure?'}, method: :delete do
  i 'Logout', class: 'fa fa-lock'
end
```

generate incorrect html

``` html
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.arb</p>
<i class="fa fa-lock">Logout</i>
```

i can use text_node only if i use `link_to` without block

``` ruby
text_node link_to('Logout', sign_out_path, method: :delete).html_safe
```

``` html
<a rel="nofollow" data-method="delete" href="/sign_out">Logout</a>
```

i think same situation will be with any helper method with block that returns html

**Comment by timoschilling** [comment]
Maybe `html_node` could be a solution.

**Comment by timoschilling** [comment]
whats happen if you do
```ruby
text_node link_to('Logout', sign_out_path, method: :delete){ i 'Logout', class: 'fa fa-lock' }.html_safe
```

**Comment by senid231** [comment]
i think you mean
 ```ruby
text_node link_to(sign_out_path, method: :delete){ i 'Logout', class: 'fa fa-lock' }.html_safe
```
it generates such html
```html
<i class="fa fa-lock">Logout</i>
<a rel="nofollow" data-method="delete" href="/sign_out"></a>
```

**Comment by seanlinsley** [comment]
That's not really surprising, because Arbre and the Rails helper methods render HTML to different buffers.

I could see two options going forward:
- update `method_missing` so that it captures any Arbre called inside the passed block into a new Arbre context, so that it doesn't get evaluated in the parent context and instead gets passed to (in this case) `link_to`
  - benefit: it would behave exactly like people expect it to
  - downside: it would be slower
- update `method_missing` to raise an error anytime an Arbre method is called inside a block that was passed to a non-arbre method
  - benefit: it prevents users from running into surprising behavior
  - benefit: it'd definitely be faster than the other option
  - downside: it limits the flexibility that people have with Rails helper methods being used inside an Arbre template

**Comment by danielricecodes** [comment]
Fast forward to 2019.  Using `text_node` with a Rails helper works.
