### ISSUE TITLE
element method_missing method showing deprecation warnings

### ISSUE THREAD

**Issue by irenehakes** [activeadmin/arbre#474]
Noted that the latest version 1.5.0 is giving deprecation warnings on the method_missing method in the element class. This seems to apply to line 179 as well though we have not seen that warning yet.

```
gems/arbre-1.5.0/lib/arbre/element.rb:183: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Not sure if the other method_missing methods will run into the same warning.

**Comment by irenehakes** [comment]
I've attempted to push up what I think would be a fix, however my user does not have permission to do so. Please advise.

**Comment by irenehakes** [comment]
Posted a potential fix on my fork. Please advise on next steps for resolution.
https://github.com/activeadmin/arbre/pull/475

**Comment by javierjulio** [comment]
First off, it would help to know what's causing this with code samples. Can you please share sample code that triggers this warning? We have nothing to go off of otherwise. The only kwargs deprecation warning I was familiar with is with ActiveAdmin's Arbre usage and that was already fixed and released awhile back. Outside of ActiveAdmin, I'm not familiar with how Arbre is used so don't want to assume it's only with ActiveAdmin.
